
### Consulta de productos
GET http://localhost:3000/productos

### Consulta de productos por id
GET http://localhost:3000/productos/11

### Consulta por disponibilidad
GET http://localhost:3000/productos/disponibles

### Crear un producto
POST http://localhost:3000/productos
Content-Type: application/json

{
  "nombre": "Laptop VICTUS",
  "precio": 799.99,
  "descripcion": "Laptop moderna con 16GB RAM y 256GB SSD",
  "disponible": true,
  "categoria_id": 2
}

### Actualizar un producto por id
PUT http://localhost:3000/productos/11
Content-Type: application/json

{
  "nombre": "Laptop VICTUS",
  "precio": 799.99,
  "descripcion": "Laptop moderna con 8GB RAM y 256GB SSD",
  "disponible": true,
  "categoria_id": 1
}
### Eliminar un producto

DELETE http://localhost:3000/productos/11
